{% set name = "deeptetrad" %}
{% set version = "1.0.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f31d213c248007aeca4606fdf64daf2c2dc5b43ccd685295ec1174ca3a717207

build:
  number: 0
  entry_points:
    - deeptetrad=deeptetrad.entry:main
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: generic

requirements:
  host:
    - pip
    - python>=3.5, <3.6.3
  run:
    - python>=3.5, <3.6.3
    - cudatoolkit 
    - tensorflow-gpu=1.12.0
    - numpy=1.16.4
    - scipy
    - keras-gpu
    - joblib
    - matplotlib
    - scikit-image
    - opencv=3.4.2
    - ipython
    - h5py   
    - pillow
    - imageio 
    - shapely
    - scikit-learn

test:
  imports:
    - deeptetrad
    - deeptetrad.utils
    - imgaug
    - imgaug.augmenters
    - imgaug.external
    - mrcnn
  commands:
    - deeptetrad --help

about:
  home: "https://github.com/abysslover/deeptetrad"
  license: "GNU General Public v3 (GPLv3)"
  license_family: "GPL3"
  license_file: "LICENSE"
  summary: "DeepTetrad: a deep learning model for fluorescent pollen-tetrad image analysis"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - abysslover