{% set name = "deeptetrad" %}
{% set version = "1.0.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f31d213c248007aeca4606fdf64daf2c2dc5b43ccd685295ec1174ca3a717207

build:
  number: 0
  entry_points:
    - deeptetrad=deeptetrad.entry:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed"
  noarch: python

requirements:
  build:
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - cudatoolkit
    - tensorflow-gpu
    - numpy >=1.16.4
    - scipy
    - keras-gpu
    - joblib
    - matplotlib
    - scikit-image
    - opencv >=3.4.2
    - ipython
    - h5py   
    - pillow
    - imageio
    - shapely >=1.6.4
    - scikit-learn

test:
  imports:
    # This needs to load libGL, but the path for that can't be injected.
    #- deeptetrad
    - deeptetrad.utils
    - mrcnn
  commands:
    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64 deeptetrad --help

about:
  home: "https://github.com/abysslover/deeptetrad"
  license: "GNU General Public v3 (GPLv3)"
  license_family: "GPL3"
  license_file: "LICENSE"
  summary: "DeepTetrad: a deep learning model for fluorescent pollen-tetrad image analysis"

extra:
  recipe-maintainers:
    - abysslover
  container:
    # opencv needs libGL
    extended-base: True
